### PR TITLE
add sonarqube chart

### PR DESCRIPTION
**Pull request by pixiake**
Signed-off-by: pixiake <guofeng@yunify.com>

### CODE REVIEW

**Comment by hlwanghl** [comment]
Looks like the latest version is 6.6.0: https://github.com/Oteemo/charts/blob/master/charts/sonarqube/Chart.yaml. Do we really need this 0.13.5?

**Comment by pixiake** [comment]
@shaowenchen  Should I update to the latest version ?

**Comment by pixiake** [comment]
@hlwanghl I have updated this chart to the  6.6.0 version. Please review again.

**Pull request merged**
