### PR TITLE
add stonedb chart

### PR DESCRIPTION
**Pull request by lxd5866**

### CODE REVIEW

**Comment by wtw1994** [comment]
helm install failed , please modify statefulset.yaml
missing required field "serviceName" in io.k8s.api.apps.v1.StatefulSetSpec

**Comment by wtw1994** [comment]
helm install failed , please modify statefulset.yaml  @lxd5866 
missing required field "serviceName" in io.k8s.api.apps.v1.StatefulSetSpec

**Comment by lxd5866** [comment]
lgtm

**Pull request closed without merging**
