### PR TITLE
fix skywalking could not be deployed.

### PR DESCRIPTION
**Pull request by JaredTan95**
related issues:

fix https://github.com/kubesphere/helm-charts/issues/66
https://github.com/kubesphere/helm-charts/pull/92 
fix https://github.com/kubesphere/helm-charts/issues/78 

Tested in kubesphere v2.1.1 and passed.

### CODE REVIEW

**Comment by JaredTan95** [comment]
image

**Comment by hlwanghl** [comment]
The chart works on Helm 2.14.3 and KubeSphere 3.0.0 UI, but not KubeSphere 2.1.1, indicating it's a bug of KS 2.1.1.

I think we need to [create an issue](https://github.com/kubesphere/kubesphere/issues/new?template=bug_report.md) against KubeSphere 2.1.1, instead of remove the license declarations above.

**Comment by JaredTan95** [comment]
> The chart works on Helm 2.14.3 and KubeSphere 3.0.0 UI, but not KubeSphere 2.1.1, indicating it's a bug of KS 2.1.1.
> 
> I think we need to [create an issue](https://github.com/kubesphere/kubesphere/issues/new?template=bug_report.md) against KubeSphere 2.1.1, instead of remove the license declarations above.

Agreed

**Pull request closed without merging**
