### PR TITLE
add ks-core chart

### PR DESCRIPTION
**Pull request by 24sama**
add ks-core chart

For more information, please see:
https://github.com/kubesphere/kubesphere/pull/5305

### CODE REVIEW

**Comment by zheng1** [comment]
@24sama CI has failed https://github.com/kubesphere/helm-charts/actions/runs/3376616532/jobs/5604553786#step:3:412

**Comment by zheng1** [comment]
@24sama  You can see it here https://github.com/helm/helm/issues/9733#issuecomment-850574262
截屏2022-11-03 10 12 15

**Comment by 24sama** [comment]
Thanks, @zheng1, the GitHub action has been passed.

**Pull request merged**
