### PR TITLE
Change externalElasticsearchUrl to externalElasticsearchHost at cc

### PR DESCRIPTION
**Pull request by mangoGoForward**
### What this PR dose?
Change externalElasticsearchUrl to externalElasticsearchHost at cc, and make the definition more clear.

### What this PR does / why we need it:
please see kubesphere/kubesphere#3829.

### Which issue(s) this PR fixes:

Fixes kubesphere/kubesphere#3829.

### CODE REVIEW

**Comment by calvinyv** [comment]
what about the users from the old version of KubeSphere CC with previous parm? do we have any migration mechanism?

**Comment by pixiake** [comment]
Thanks for this contribution.  And https://github.com/kubesphere/ks-installer/pull/1798 has been merged.

But v3.2.0 has beeen released and does not contain this change. Therefore, I think it is more appropriate to merge this pr and https://github.com/kubesphere/kubekey/pull/742 after the release of the next version, otherwise it will cause v3.2.0 to fail to find `externalElasticsearchUrl` in the installation process.

**Comment by mangoGoForward** [comment]
> Thanks for this contribution. And [kubesphere/ks-installer#1798](https://github.com/kubesphere/ks-installer/pull/1798) has been merged.
> 
> But v3.2.0 has been released and does not contain this change. Therefore, I think it is more appropriate to merge this pr and [kubesphere/kubekey#742](https://github.com/kubesphere/kubekey/pull/742) after the release of the next version, otherwise it will cause v3.2.0 to fail to find `externalElasticsearchUrl` in the installation process.

Ok. And do we need some compatibility measures for old version like above logic?

**Comment by pixiake** [comment]
Adding only the logic above should not be fully compatible with the old version,  because the install process is already included in the image of the old version.

**Comment by mangoGoForward** [comment]
> Adding only the logic above should not be fully compatible with the old version, because the install process is already included in the image of the old version.

I have no idea to avoid now, if you have any idea, please share with me, Thanks a lot.

**Comment by pixiake** [comment]
I think the best way at present may be to update the chart of ks-installer to v3.2.0 first, and then the later new version can use `externalElasticsearchHost`.

**Comment by FeynmanZhou** [comment]
> I think the best way at present may be to update the chart of ks-installer to v3.2.0 first, and then the later new version can use `externalElasticsearchHost`.

@pixiake Do we need to create a GitHub issue to track the ks-installer Helm Chart upgrade?

**Comment by mangoGoForward** [comment]
> I think the best way at present may be to update the chart of ks-installer to v3.2.0 first, and then the later new version can use `externalElasticsearchHost`.

Ok.

**Comment by pixiake** [comment]
> Do we need to create a GitHub issue to track the ks-installer Helm Chart upgrade? If so, it could be a good first issue.

Yes，I have created an issue https://github.com/kubesphere/helm-charts/issues/190 .

**Comment by mangoGoForward** [comment]
Do we still need to modify `externalElasticsearchUrl` to `externalElasticsearchHost`? @pixiake

**Pull request closed without merging**
