### PR TITLE
Update the nfs-provisioner image to avoid bugs in K8S 1.20 and newer

### PR DESCRIPTION
**Pull request by dkeven**
/kind bug

In K8S v1.20 and newer, the current version of nfs-provisioner image will not work, refer: https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/25

And many KS users have reported this same issue in the Chinese forum, related posts in just the past week
https://kubesphere.com.cn/forum/d/4676-openebsnfsmonitoring-prometheus/8
https://kubesphere.com.cn/forum/d/4752-v310nfs-client-provisionerpvcpending
https://kubesphere.com.cn/forum/d/4706-centos7kubesphere-v31-ha

This bug has been fixed in the new version, and is backwards compatible with the old one, so we need to change this chart since it's in the NFS example of the KS Official doc:
https://kubesphere.com.cn/en/docs/installing-on-linux/persistent-storage-configurations/install-nfs-client/
https://v3-0.docs.kubesphere.io/docs/installing-on-linux/persistent-storage-configurations/install-nfs-client/

### CODE REVIEW

**Comment by zheng1** [comment]
1. Can you push the nfs-subdir-external-provisioner image to dockerhub? k8s.gcr.io may not be accessible in some environments.
2. Please update the version in Chart.yaml

**Comment by dkeven** [comment]
> 1. Can you push the nfs-subdir-external-provisioner image to dockerhub? k8s.gcr.io may not be accessible in some environments.
> 2. Please update the version in Chart.yaml

Okay, will do

**Comment by dkeven** [comment]
@zryfish Can you create a `nfs-subdir-external-provisioner` repo under `kubesphere` on Dockerhub for me to push?

Or you can help me out by pushing the `k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2` image to `kubesphere/nfs-subdir-external-provisioner:v4.0.2`.

Thanks

**Comment by zheng1** [comment]
Here is some error:
```
Error response from daemon: pull access denied for registry.cn-beijing.aliyuncs.com/kubesphereio/nfs-subdir-external-provisioner, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by dkeven** [comment]
> Here is some error:
> 
> ```
> Error response from daemon: pull access denied for registry.cn-beijing.aliyuncs.com/kubesphereio/nfs-subdir-external-provisioner, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
> ```

This image will be synced when this PR is merged:  https://github.com/kubesphere/image-sync-config/pull/9

**Pull request merged**
