### PR TITLE
Add InAccel FPGA Operator

### PR DESCRIPTION
**Pull request by eliaskoromilas**
### App Introduction

[InAccel FPGA Operator](https://artifacthub.io/packages/helm/inaccel/fpga-operator) is a cloud-native method to standardize and automate the deployment of all the necessary components for provisioning FPGA-enabled Kubernetes systems. FPGA Operator delivers a universal accelerator orchestration and monitoring layer, to automate scalability and lifecycle management of containerized FPGA applications on any Kubernetes cluster.

The FPGA operator also allows cluster admins to manage their remote FPGA-powered servers the same way they manage CPU-based systems, but also regular users to target particular FPGA types and explicitly consume FPGA resources in their workloads. This makes it easy to bring up a fleet of remote systems and run accelerated applications without additional technical expertise on the ground.

### CODE REVIEW

**Comment by eliaskoromilas** [comment]
I would also propose a new [category icon](https://github.com/kubesphere/openpitrix-jobs/blob/master/import-config.yaml#L2):
```
# map category name to icon
categoryIcon:
...
  "Infrastructure": "nodes"
```

The new category could be used for apps that manage node resources in general (e.g. storage, network, etc.).

**Comment by calvinyv** [comment]
@zheng1 
/area app-management

**Comment by FeynmanZhou** [comment]
@eliaskoromilas Awesome. Now I can see FPGA Operator from my existing KubeSphere cluster. 
image

**Comment by eliaskoromilas** [comment]
> @eliaskoromilas Awesome. Now I can see FPGA Operator from my existing KubeSphere cluster.

@FeynmanZhou We also tested this and it works like a charm in our local cluster. :rocket: 

It seems though that the following Chart annotations were not taken into account:

```yaml
annotations:
  app.kubesphere.io/category: Infrastructure
  app.kubesphere.io/display-name: InAccel FPGA Operator
```

I think it would be great if similar annotations were also used to populate more fields in the App Store (e.g. **App Introduction**).

fpga-operator

**Homepage** and **Keywords** fields are not parsed either.

**Comment by FeynmanZhou** [comment]
> > @eliaskoromilas Awesome. Now I can see FPGA Operator from my existing KubeSphere cluster.
> 
> @FeynmanZhou We also tested this and it works like a charm in our local cluster. 🚀
> 
> It seems though that the following Chart annotations were not taken into account:
> 
> ```yaml
> annotations:
>   app.kubesphere.io/category: Infrastructure
>   app.kubesphere.io/display-name: InAccel FPGA Operator
> ```
> 
> I think it would be great if similar annotations were also used to populate more fields in the App Store (e.g. **App Introduction**).
> 
> fpga-operator
> 
> **Homepage** and **Keywords** fields are not parsed either.

Thanks for pointing out this issue. It looks abnormal. 

Hi @xyz-li @kubesphere/sig-console @kubesphere/sig-apps , could you please help to take a look at it?

**Pull request merged**
