### PR TITLE
Upgrade ks-installer to 3.2.1

### PR DESCRIPTION
**Pull request by mangoGoForward**
Signed-off-by: mango <xu.weiKyrie@foxmail.com>

### What this PR dose?
Upgrade ks-installer chart to v3.2.1

### What this PR does / why we need it:
please see #190.

### CODE REVIEW

**Comment by FeynmanZhou** [comment]
Hi team @kubesphere/sig-installation , could you please help to review this PR? Thanks.

**Comment by xyz-li** [comment]
@mangoGoForward 
There is a bug in the CI workflow before you push this commit. Can you rebase the commit and push it again?

**Comment by mangoGoForward** [comment]
> @mangoGoForward There was a bug in the CI workflow before you push this commit. Can you rebase the commit and push it again?

Thanks, I have merged remote-tracking branch.

**Pull request merged**
