### PR TITLE
Parameterize detach retry max time

### PR DESCRIPTION
**Pull request by dkeven**
Signed-off-by: dkeven <keven@kubesphere.io>

Fixes https://github.com/kubesphere/helm-charts/issues/175

This is a corresponding PR of https://github.com/yunify/qingcloud-csi/pull/185

This chart is deployable only after that PR is merged & new container image is pushed.

### CODE REVIEW

**Comment by dkeven** [comment]
/hold

There might be more change to the command args.

**Comment by dkeven** [comment]
/unhold

There are no more changes to the command args, as the chart template did not use the `retry-interval-max` option, which https://github.com/yunify/qingcloud-csi/pull/186 removes.

**Review by stoneshi-yunify — APPROVED** [review]
/lgtm

**Pull request merged**
