### PR TITLE
Try to add Databend to KubeSphere App Store

### PR DESCRIPTION
**Pull request by PsiACE**
## App Introduction:

- GitHub: https://github.com/datafuselabs/databend
- Website: https://databend.rs/

Databend is an open-source Elastic and Workload-Aware modern cloud data warehouse.

Databend uses the latest techniques in vectorized query processing to allow you to do blazing-fast data analytics on object storage([S3](https://aws.amazon.com/s3/), [Azure Blob](https://azure.microsoft.com/en-us/services/storage/blobs/), [Google Cloud Storage](https://cloud.google.com/storage/), [Huawei Cloud OBS](https://www.huaweicloud.com/intl/en-us/product/obs.html) or [MinIO](https://min.io/)).

### CODE REVIEW

**Comment by PsiACE** [comment]
It looks like the lockfile may need to be removed

**Comment by wubx** [comment]
LGTM

**Comment by zheng1** [comment]
@PsiACE Can you submit those charts to the [stable](https://github.com/kubesphere/helm-charts/tree/master/src/stable) repo? This will automatically put the chart in the KubeSphere v3.2 and v3.3 app store

**Comment by PsiACE** [comment]
> Can you submit those charts to the [stable](https://github.com/kubesphere/helm-charts/tree/master/src/stable) repo? 

@zheng1 Already done so, thanks.

**Comment by isyes** [comment]
@PsiACE  the charts should include the dependencies chart/ directory, update the chart's dependencies, download the dependencies to the charts/ directory.

**Comment by PsiACE** [comment]
cc @isyes done

**Pull request merged**
