### PR TITLE
Add Apache Pulsar Helm Chart

### PR DESCRIPTION
**Pull request by tuhaihe**

### CODE REVIEW

**Comment by tuhaihe** [comment]
@FeynmanZhou @zheng1 PTAL. If any questions, please let me know. Thanks.

**Comment by FeynmanZhou** [comment]
Hi @tuhaihe , 

As we see Sherlock has verified the [installation of Apache Pulsar on KubeSphere](https://dzone.com/articles/pulsar-on-kubesphere-installing-distributed-messaging-and-streaming-platform) for the basic use case, I think this chart could be submitted to [stable folder](https://github.com/kubesphere/helm-charts/tree/master/src/stable) directly. You can update the destination folder from `/src/test` to `/src/stable`.

**Comment by Sherlock113** [comment]
@tuhaihe Hi, this pull request can be closed. I created a new pull request  https://github.com/kubesphere/helm-charts/pull/222 to submit the Pulsar Chart package to `/src/stable`. Thanks!

**Comment by tuhaihe** [comment]
@Sherlock113 Great work, thanks!

**Pull request closed without merging**
