### PR TITLE
Add Pulsar to the KubeSphere App Store

### PR DESCRIPTION
**Pull request by Sherlock113**
Add Pulsar to the KubeSphere App Store.

This pull request replaces https://github.com/kubesphere/helm-charts/pull/221.

Tell me if you have any questions. Thanks.

### CODE REVIEW

**Comment by Sherlock113** [comment]
/assign @zheng1 @FeynmanZhou @xyz-li 
Thanks!

**Comment by xyz-li** [comment]
I deployed the chart and set all the `replicaCount` to 1.  The pod `broker-0` and `proxy-0`  have been in the initializing state.
```
NAME                                        READY   STATUS      RESTARTS   AGE
pulsar-vhjj7x-bookie-0                      1/1     Running     0          17m
pulsar-vhjj7x-bookie-init-r8fwz             0/1     Completed   0          17m
pulsar-vhjj7x-broker-0                      0/1     Init:1/2    0          17m
pulsar-vhjj7x-grafana-8c86b4c4b-879mq       1/1     Running     0          17m
pulsar-vhjj7x-prometheus-7d74c96857-sncp8   1/1     Running     0          17m
pulsar-vhjj7x-proxy-0                       0/1     Init:1/2    0          17m
pulsar-vhjj7x-pulsar-init-pfnz4             0/1     Completed   0          17m
pulsar-vhjj7x-recovery-0                    1/1     Running     0          17m
pulsar-vhjj7x-toolset-0                     1/1     Running     0          17m
pulsar-vhjj7x-zookeeper-0                   1/1     Running     0          17m
```
```
pulsar cluster pulsar-vhjj7x isn't initialized yet ... check in 10 seconds ...
pulsar cluster pulsar-vhjj7x isn't initialized yet ... check in 10 seconds ...
```

**Comment by xyz-li** [comment]
1. Run the script
image
2. Set initialize to true
```
pulsar-helm-chart git:(master) helm get    values -n test  pulsar-mini  |grep initialize
initialize: true
```

But bookkeeper is in Initializing state
image
image

**Comment by Sherlock113** [comment]
This is strange...I tried it again on Google Cloud. And it actually worked:
image
I am wondering if it has something to do with network?

**Comment by xyz-li** [comment]
Sorry, I missed this comment.
```
  # the number of zookeeper servers to run. it should be an odd number larger than or equal to 3.
  replicaCount: 1
```
/lgtm

**Pull request merged**
