### PR TITLE
upgrade Chaos Mesh to v2.0.4

### PR DESCRIPTION
**Pull request by cwen0**
Signed-off-by: cwen0 <cwenyin0@gmail.com>  

Chaos Mesh v2.0.4 release notes: https://github.com/chaos-mesh/chaos-mesh/releases/tag/v2.0.4

### CODE REVIEW

**Comment by cwen0** [comment]
@FeynmanZhou PTAL

**Comment by zheng1** [comment]
Hi, @cwen0 , please update the version in Chart.yaml
/cc @xyz-li

**Comment by xyz-li** [comment]
I think it's better to update the version of the chart since you have updated the tag of the image.

**Comment by cwen0** [comment]
> 

Fixed

**Comment by cwen0** [comment]
> Hi, @cwen0 , please update the version in Chart.yaml /cc @xyz-li

Fixed

**Comment by cwen0** [comment]
> I think it's better to update the version of the chart since you have updated the tag of the image.

Fixed

**Pull request merged**
