### PR TITLE
add skywalking 6.5.0 support

### PR DESCRIPTION
**Pull request by runzexia**

### CODE REVIEW

**Comment by chinazj** [comment]
This is the first time that I formally submit PR. if there is any error, please point out the problem.

**Comment by innerpeacez** [comment]
SkyWalking Chart 6.6 will be released.Will you continue to support it? :)

**Comment by runzexia** [comment]
> SkyWalking Chart 6.6 will be released.Will you continue to support it? :)

Yes, we want to add 6.6.0 to kubesphere. However, a problem we are encountering now is that skywalking only provides helm v3 charts, and the kubesphere app store currently only supports helm v2 charts.
I hope skywalking can provide helm v2 chart, or we cooperate to maintain this part.

**Comment by hlwanghl** [comment]
Remove `charts/elasticsearch-1.32.3.tgz`, as it will be automatically packaged into final chart file.

**Comment by innerpeacez** [comment]
SkyWalking Team will not maintain helm 2 for the time being.May be maintained in the future.:) @runzexia

**Pull request merged**
